replicaCount: 1

image:
  repository: primev/primev
  pullPolicy: IfNotPresent
  tag: "1.2.0-indexer-rc5"

nameOverride: ""
fullnameOverride: "l1-indexer"

podAnnotations: {}

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}

# Indexer configuration
indexer:
  # Chain type: "mevcommit" or "l1"
  chainType: "l1"
  extraArgs:
  - "-start-block=21153543"

  # Mode: forward or backfill
  mode: "forward"

  # Follower or L1 URL
  rpcUrl: "https://ethereum-rpc.publicnode.com"
    
  # ABI directory - different for each chain type
  abiDir: "/l1-abi"
  #abiDir: "/contracts-abi/abi"  # For mevcommit (baked into image)
  # For l1, override to: "/l1-abi"

  # DB for mevcommit or eth
  dsn: "root:@tcp(starrocks-cluster-fe-service.starrocks.svc.cluster.local:9030)/eth?parseTime=true&interpolateParams=true"
  
  batchSize: 50

  # Poll interval for forward mode
  pollInterval: "100ms"
  
  # Backfill settings (only used when mode is "backfill")
  backfill:
    fromBlock: 0
    toBlock: 0
