# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bridge-relayer.fullname" . }}-secrets
  labels:
    {{- include "bridge-relayer.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{ .Values.config.postgresql.password | b64enc }}
