- name: Destroy Nomad Jobs
  hosts: nomad_clients

  tasks:
    - name: Destroy | Nomad jobs
      ansible.builtin.shell: |
        for job in $(nomad job status | awk 'NR > 1 {print $1}'); do
          nomad stop -purge "${job}"
        done
      args:
        executable: bash
