jobs:
  - name: datadog-agent-logs-collector
    template: datadog-agent.nomad.j2
    count: 1
    type: logs
    ports:
      - tcp:
          to: 10500

  - name: mev-commit-geth-bootnode1
    template: mev-commit-geth.nomad.j2
    count: 1
    ports:
      - metrics:
          to: 6060
        http:
          static: 8545
          to: 8545
        ws:
          static: 8546
          to: 8546
        p2p:
          to: 30301
    env:
      ip: 0.0.0.0
      public-ip: 0.0.0.0
      net-restrict: 0.0.0.0/0
      type: bootnode

  - name: mev-commit-geth-signer-node1
    template: mev-commit-geth.nomad.j2
    count: 1
    ports:
      - metrics:
          to: 6060
        p2p:
          to: 30311
    env:
      ip: 0.0.0.0
      net-restrict: 0.0.0.0/0
      type: signer
      sync-mode: snap
      block-address: "0xd9cd8E5DE6d55f796D980B818D350C0746C25b97"

  - name: mev-commit-geth-member-node
    template: mev-commit-geth.nomad.j2
    count: 1
    ports:
      - metrics:
          to: 6060
        http:
          static: 8555
          to: 8545
        ws:
          static: 8556
          to: 8546
        p2p:
          to: 30311
    env:
      ip: 0.0.0.0
      public-ip: "{{ ansible_facts['default_ipv4']['address'] }}"
      net-restrict: 0.0.0.0/0
      type: member
      sync-mode: snap

  - name: deploy-contracts
    template: deploy-contracts.nomad.j2
    count: 1
    chain-id: 17864

  - name: mev-commit-bootnode1
    template: mev-commit.nomad.j2
    count: 1
    secrets:
      keystore: bootnode1
    ports:
      - metrics:
          to: 13523
        http:
          static: 13523
          to: 13523
        p2p:
          static: 13522
          to: 13522
    env:
      type: bootnode
      tls-crt-file: "{{ tls_crt_file }}"
      tls-key-file: "{{ tls_key_file }}"

  - name: mev-commit-provider-node1
    template: mev-commit.nomad.j2
    count: 1
    secrets:
      keystore: provider1
    ports:
      - metrics:
          to: 13523
        http:
          static: 13533
          to: 13523
        p2p:
          to: 13522
        rpc:
          static: 13534
          to: 13524
    env:
      type: provider
      nat-address: "{{ ansible_facts['default_ipv4']['address'] }}"
      tls-crt-file: "{{ tls_crt_file }}"
      tls-key-file: "{{ tls_key_file }}"
      preconf-contract-address: "{{ preconf_contract_address }}"
      blocktracker-contract-address: "{{ blocktracker_contract_address }}"
      bidder-registry-contract-address: "{{ bidder_registry_contract_address }}"
      provider-registry-contract-address: "{{ provider_registry_contract_address }}"

  - name: mev-commit-provider-node1-funder
    template: mev-commit-funder.nomad.j2
    count: 1
    target_type: provider
    target_name: mev-commit-provider-node1

  - name: mev-commit-oracle
    template: mev-commit-oracle.nomad.j2
    count: 1
    ports:
      - db:
          static: 5432
          to: 5432
        http:
          static: 8080
          to: 8080
    env:
      l1-rpc-url: https://ethereum-holesky-rpc.publicnode.com
      preconf-contract-address: "{{ preconf_contract_address }}"
      blocktracker-contract-address: "{{ blocktracker_contract_address }}"
      bidder-registry-contract-address: "{{ bidder_registry_contract_address }}"
      provider-registry-contract-address: "{{ provider_registry_contract_address }}"
      oracle-contract-address: "{{ oracle_contract_address }}"

  - name: mev-commit-bidder-node1
    template: mev-commit.nomad.j2
    count: 1
    secrets:
      keystore: bidder1
    ports:
      - metrics:
          to: 13523
        http:
          static: 13532
          to: 13523
        p2p:
          to: 13522
        rpc:
          static: 13544
          to: 13524
    env:
      type: bidder
      tls-crt-file: "{{ tls_crt_file }}"
      tls-key-file: "{{ tls_key_file }}"
      preconf-contract-address: "{{ preconf_contract_address }}"
      blocktracker-contract-address: "{{ blocktracker_contract_address }}"
      bidder-registry-contract-address: "{{ bidder_registry_contract_address }}"
      provider-registry-contract-address: "{{ provider_registry_contract_address }}"

  - name: mev-commit-bidder-node1-funder
    template: mev-commit-funder.nomad.j2
    count: 1
    target_type: bidder
    target_name: mev-commit-bidder-node1

  - name: mev-commit-provider-emulator-node1
    template: mev-commit-emulator.nomad.j2
    count: 1
    target_type: provider
    target_name: mev-commit-provider-node1
    ports:
      - metrics:
          to: 8080

  - name: mev-commit-bidder-emulator-node1
    template: mev-commit-emulator.nomad.j2
    count: 1
    target_type: bidder
    target_name: mev-commit-bidder-node1
    ports:
      - metrics:
          to: 8080

  - name: mev-commit-bridge
    template: mev-commit-bridge.nomad.j2
    count: 1
    ports:
      - metrics:
          to: 8080
    env:
      l1-chain-id: 17000
      l1-rpc-url: https://ethereum-holesky.publicnode.com

  - name: datadog-agent-metrics-collector
    template: datadog-agent.nomad.j2
    count: 1
    type: metrics
