env: "devnet"
openssl_dir: "/etc/ssl"
private_keys_dir: "{{ openssl_dir }}/private"
certificates_dir: "{{ openssl_dir }}/certs"
ca_certificates_dir: "/usr/local/share/ca-certificates"
server_common_name: "mev-commit_{{ env }}.mev-commit.primev.xyz"
tls_crt_file: "{{ certificates_dir }}/{{ server_common_name }}.crt"
tls_key_file: "{{ private_keys_dir }}/{{ server_common_name }}.key"
tls_ca_crt_file: "{{ ca_certificates_dir }}/ca-{{ server_common_name }}.crt"

jobs:
  - name: datadog-agent-logs-collector
    template: datadog-agent.nomad.j2
    count: 1
    type: logs
    ports:
      - tcp:
          to: 10500

  - name: mev-commit-geth-bootnode1
    template: mev-commit-geth.nomad.j2
    count: 1
    ports:
      - metrics:
          to: 6060
        http:
          static: 8545
          to: 8545
        ws:
          static: 8546
          to: 8546
        p2p:
          to: 30301
    env:
      ip: 0.0.0.0
      public_ip: 0.0.0.0
      net_restrict: 0.0.0.0/0
      type: bootnode

  - name: mev-commit-geth-signer-node1
    template: mev-commit-geth.nomad.j2
    count: 1
    ports:
      - metrics:
          to: 6060
        p2p:
          to: 30311
    env:
      ip: 0.0.0.0
      net_restrict: 0.0.0.0/0
      type: signer
      sync_mode: snap
      block_address: "0xd9cd8E5DE6d55f796D980B818D350C0746C25b97"

  - name: mev-commit-geth-member-node
    template: mev-commit-geth.nomad.j2
    count: 1
    ports:
      - metrics:
          to: 6060
        http:
          static: 8555
          to: 8545
        ws:
          static: 8556
          to: 8546
        p2p:
          to: 30311
    env:
      ip: 0.0.0.0
      public_ip: "{{ ansible_facts['default_ipv4']['address'] }}"
      net_restrict: 0.0.0.0/0
      type: member
      sync_mode: snap

  - name: deploy-contracts
    template: deploy-contracts.nomad.j2
    count: 1
    chain-id: 17864

  - name: mev-commit-bootnode1
    template: mev-commit.nomad.j2
    count: 1
    secrets:
      keystore: bootnode1
    ports:
      - metrics:
          to: 13523
        http:
          static: 13523
          to: 13523
        p2p:
          static: 13522
          to: 13522
    env:
      type: bootnode
      tls_crt_file: "{{ tls_crt_file }}"
      tls_key_file: "{{ tls_key_file }}"

  - name: mev-commit-provider-node1
    template: mev-commit.nomad.j2
    count: 1
    secrets:
      keystore: provider1
    ports:
      - metrics:
          to: 13523
        http:
          static: 13533
          to: 13523
        p2p:
          to: 13522
        rpc:
          static: 13534
          to: 13524
    env:
      type: provider
      nat_address: "{{ ansible_facts['default_ipv4']['address'] }}"
      tls_crt_file: "{{ tls_crt_file }}"
      tls_key_file: "{{ tls_key_file }}"

  - name: mev-commit-provider-node1-funder
    template: mev-commit-funder.nomad.j2
    count: 1
    target_type: provider
    target_name: mev-commit-provider-node1

  - name: mev-commit-oracle
    template: mev-commit-oracle.nomad.j2
    count: 1
    ports:
      - db:
          static: 5432
          to: 5432
        http:
          static: 8080
          to: 8080
    env:
      l1_rpc_url: https://ethereum-holesky-rpc.publicnode.com

  - name: mev-commit-bidder-node1
    template: mev-commit.nomad.j2
    count: 1
    secrets:
      keystore: bidder1
    ports:
      - metrics:
          to: 13523
        http:
          static: 13532
          to: 13523
        p2p:
          to: 13522
        rpc:
          static: 13544
          to: 13524
    env:
      type: bidder
      tls_crt_file: "{{ tls_crt_file }}"
      tls_key_file: "{{ tls_key_file }}"

  - name: mev-commit-bidder-node1-funder
    template: mev-commit-funder.nomad.j2
    count: 1
    target_type: bidder
    target_name: mev-commit-bidder-node1

  - name: mev-commit-provider-emulator-node1
    template: mev-commit-emulator.nomad.j2
    count: 1
    target_type: provider
    target_name: mev-commit-provider-node1
    ports:
      - metrics:
          to: 8080

  - name: mev-commit-bidder-emulator-node1
    template: mev-commit-emulator.nomad.j2
    count: 1
    target_type: bidder
    target_name: mev-commit-bidder-node1
    ports:
      - metrics:
          to: 8080
    env:
      l1_rpc_url: https://ethereum-holesky-rpc.publicnode.com

  - name: mev-commit-bridge
    template: mev-commit-bridge.nomad.j2
    count: 1
    ports:
      - metrics:
          to: 8080
    env:
      l1_chain_id: 17000
      l1_rpc_url: https://ethereum-holesky.publicnode.com

  - name: datadog-agent-metrics-collector
    template: datadog-agent.nomad.j2
    count: 1
    type: metrics
