apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.keystore.persistentVolumeClaim }}
  labels:
    {{- include "mev-oracle.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.keystore.size | default "1Gi" }}
  storageClassName: {{ .Values.keystore.storageClassName | quote }}
