linters-settings:
  gofmt:
    simplify: true
  gocritic:
    enabled-tags:
      - style
      - performance
  errcheck:
    check-type-assertions: true
    check-blank: true

linters:
  presets:
    - sql
    - test
    - bugs
    - style
    - format
    - import
    - unused
    - comment
    - complexity
    - performance
  disable:
    - gomoddirectives
    - paralleltest
    - musttag # TODO(mrekucci): re-enable when external/geth is bumped to go1.21

run:
  timeout: 15m
  concurrency: 4

issues:
  new: true
