{{- if ne .Values.role "bootnode" }}
[Node.P2P]
{{- if .Values.nodeConfig.bootstrapNodes }}
  BootstrapNodes = [
{{- range $index, $peer := .Values.nodeConfig.bootstrapNodes }}
    {{- if $index }},{{ end }}
    "{{ $peer }}"
{{- end }}
  ]
{{- end }}
{{- if .Values.nodeConfig.staticPeers }}
  StaticNodes = [
{{- range $index, $peer := .Values.nodeConfig.staticPeers }}
    {{- if $index }},{{ end }}
    "{{ $peer }}"
{{- end }}
  ]
{{- end }}
{{- else }}
# No bootstrap or static peers needed for bootnode
[Node.P2P]
{{- end }}
