apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ethereum-poa.fullnameWithRole" . }}-scripts
  labels:
    {{- include "ethereum-poa.labels" . | nindent 4 }}
data:
  init-genesis.sh: |
{{ tpl (.Files.Get "files/init-genesis.sh") . | indent 4 }}
  init-nodekey.sh: |
{{ tpl (.Files.Get "files/init-nodekey.sh") . | indent 4 }}
  config.toml: |
{{ tpl (.Files.Get "files/config.toml") . | indent 4 }}
  
{{- if .Values.probes.enabled }}
  syncProbe.sh: |
{{ tpl (.Files.Get "files/syncProbe.sh") . | indent 4 }}
{{- end }}
