{{- if eq .Values.role "signer" }}

{{- /* Password Secret */ -}}
{{- if .Values.signer.password.externalSecret.enabled }}
# Password External Secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.signer.password.secretName }}
  labels:
    {{- include "ethereum-poa.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.signer.password.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.signer.password.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.signer.password.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.signer.password.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: password.txt
      remoteRef:
        key: {{ .Values.signer.password.externalSecret.awsSecretName }}
        property: password
{{- else if .Values.signer.password.value }}
# Local Password Secret (insecure)
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.signer.password.secretName }}
  labels:
    {{- include "ethereum-poa.labels" . | nindent 4 }}
type: Opaque
data:
  password.txt: {{ .Values.signer.password.value | b64enc }}
{{- end }}
---

{{- /* Private Key Secret */ -}}
{{- if eq .Values.signer.nodeBootstrapMethod "signerPrivateKey" }}
{{- if .Values.signer.signerPrivateKey.externalSecret.enabled }}
# Private Key External Secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.signer.signerPrivateKey.secretName }}
  labels:
    {{- include "ethereum-poa.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.signer.signerPrivateKey.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.signer.signerPrivateKey.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.signer.signerPrivateKey.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.signer.signerPrivateKey.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: signer-key
      remoteRef:
        key: {{ .Values.signer.signerPrivateKey.externalSecret.awsSecretName }}
        property: privateKey
{{- else if .Values.signer.signerPrivateKey.value }}
# Local Private Key Secret (insecure)
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.signer.signerPrivateKey.secretName }}
  labels:
    {{- include "ethereum-poa.labels" . | nindent 4 }}
type: Opaque
data:
  signer-key: {{ .Values.signer.signerPrivateKey.value | b64enc }}
{{- end }}
{{- end }}

{{- end }}
