{{- if and (eq .Values.role "signer") .Values.signer.passwordExternalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.signer.passwordSecretName }}
  labels:
    {{- include "ethereum-poa.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.signer.passwordExternalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.signer.passwordExternalSecret.secretStoreRef.name }}
    kind: {{ .Values.signer.passwordExternalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.signer.passwordSecretName }}
  data:
    - secretKey: password.txt
      remoteRef:
        key: {{ .Values.signer.passwordExternalSecret.awsSecretName }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.signer.privateKeySecretName }}
  labels:
    {{- include "ethereum-poa.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.signer.privateKeyExternalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.signer.privateKeyExternalSecret.secretStoreRef.name }}
    kind: {{ .Values.signer.privateKeyExternalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.signer.privateKeySecretName }}
  data:
    - secretKey: signer-key
      remoteRef:
        key: {{ .Values.signer.privateKeyExternalSecret.awsSecretName }}
{{- end }}
