priv-key-file: "example_config/relayer_key"
log-level: "debug"
l1-rpc-url: "http://l1-bootnode:8545"
settlement-rpc-url: "http://sl-bootnode:8545"
l1-contract-addr: "0xe7B3D66A143Bfb85Cd980d1577Ba52f68F8f5809"
settlement-contract-addr: "0xC157631f4aaaaabAB864544d743c5726a68C85a4"
