apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "erigon-snode.fullname" . }}-scripts
  labels:
    {{- include "erigon-snode.labels" . | nindent 4 }}
data:
  create-jwt.sh: |
    #!/bin/sh
    set -e
    if [ -f /shared/jwt ]; then
      echo "[create-jwt] JWT already exists, skipping creation"
      exit 0
    fi
    echo "[create-jwt] copying JWT from secret to /shared/jwt"
    cp /secrets/jwt /shared/jwt
    chmod 600 /shared/jwt
  download-genesis.sh: |
    #!/bin/sh
    set -e
    echo "[download-genesis] ensuring /shared permissions"
    mkdir -p /shared
    chmod 777 /shared
    
    if [ -f /shared/genesis.json ]; then
      echo "[download-genesis] genesis.json already exists, skipping download"
      exit 0
    fi
    
    echo "[download-genesis] downloading genesis.json"
    wget -O /shared/genesis.json {{ .Values.genesis.url }}
  init-erigon.sh: |
    #!/bin/sh
    set -e
    
    # Check if erigon has already been initialized
    if [ -f {{ .Values.erigon.datadir }}/chaindata/CURRENT ] || [ -f {{ .Values.erigon.datadir }}/chaindata/LOCK ]; then
      echo "[init-erigon] Erigon already initialized, skipping init"
      exit 0
    fi
    
    echo "[init-erigon] initializing erigon with genesis.json"
    erigon --datadir {{ .Values.erigon.datadir }} init /shared/genesis.json
