{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "erigon-snode.fullname" . }}-rpc
  labels:
    {{- include "erigon-snode.labels" . | nindent 4 }}
    app.kubernetes.io/component: rpc-ingress
  {{- with .Values.ingress.rpc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.rpc.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.rpc.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.rpc.path }}
            pathType: {{ .Values.ingress.rpc.pathType }}
            backend:
              service:
                name: {{ include "erigon-snode.fullname" . }}-erigon
                port:
                  name: http
{{- end }}
