apiVersion: v1
kind: Secret
metadata:
  name: {{ include "erigon-snode.fullname" . }}-jwt
  labels:
    {{- include "erigon-snode.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt: {{ .Values.jwt.token | quote }}
