- name: Destroy Cluster
  hosts: nomad_clients
  gather_facts: no

  vars:
    version: "unknown"
    profile: "unknown"
    nomad_vars_path: "nomad/jobs"

  pre_tasks:
    - name: Include Environment Definitions
      include_vars:
        file: variables/environments.yml

    - name: Check Environment Name
      ansible.builtin.assert:
        that:
          - env is defined
          - env | length > 0
          - env in environments
        fail_msg: "The environment name is not set correctly."
        success_msg: "The environment name is set to: {{ env }}."

  tasks:
    - name: Stop and Purge Jobs
      ansible.builtin.shell: |
        for job in $(nomad job status -json | jq -r 'sort_by(.Allocations[0].CreateTime) | reverse | .[].Summary.JobID'); do
          if [ "${job}" != "null" ]; then
            nomad stop -purge "${job}"
          fi
        done
        nomad var purge "nomad/jobs"
        nomad system gc
        rm -rf /var/lib/mev-commit/{{ env }}/*
      args:
        executable: bash
      become: yes
