- name: Destroy Cluster
  hosts: nomad_clients
  gather_facts: no

  tasks:
    - name: Stop and Purge Jobs
      ansible.builtin.shell: |
        for job in $(nomad job status -json | jq -r '.[].Summary.JobID'); do
          if [ "${job}" != "null" ]; then
            nomad stop -purge "${job}"
          fi
        done
      args:
        executable: bash

    - name: Purge Cluster
      ansible.builtin.shell: |
        nomad var purge "nomad/jobs"
        nomad system gc
      args:
        executable: bash
