apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chain-indexer.fullname" . }}-manifest
  labels:
    {{- include "chain-indexer.labels" . | nindent 4 }}
data:
  {{- if eq .Values.indexer.chainType "mevcommit" }}
  manifest.json: {{ .Files.Get "abi-manifest-json/mevcommit-manifest.json" | quote }}
  {{- else if eq .Values.indexer.chainType "l1" }}
  manifest.json: {{ .Files.Get "abi-manifest-json/l1-manifest.json" | quote }}
  {{- end }}
---
{{- if eq .Values.indexer.chainType "l1" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chain-indexer.fullname" . }}-l1-abi
  labels:
    {{- include "chain-indexer.labels" . | nindent 4 }}
data:
  {{- range $path, $_ := .Files.Glob "l1-abis/*.abi" }}
  {{ base $path }}: {{ $.Files.Get $path | quote }}
  {{- end }}
{{- end }}
