version: 1

project_name: points-service
dist: /tmp/dist/points-service

builds:
  - env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-musl-gcc
    goos:
      - linux
    goarch:
      - amd64
    dir: .
    binary: "{{ .ProjectName }}"
    flags:
      - -v
      - -trimpath
      - -tags=sqlite3
    ldflags:
      - -extldflags "-static"

archives:
  - format: tar.gz
    name_template: >-
      {{- .Binary }}_
      {{- with index .Env "RELEASE_VERSION" -}}
        {{ . }}
      {{- else -}}
        {{- if .IsSnapshot }}{{ .ShortCommit }}
        {{- else }}{{ .Version }}
        {{- end }}
      {{- end -}}
      {{- with index .Env "DIRTY_SUFFIX" -}}
      {{ . }}
      {{- end -}}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}
      {{- end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: >-
    {{ .ProjectName }}_
    {{- with index .Env "RELEASE_VERSION" -}}
      {{ . }}
    {{- else -}}
      {{- if .IsSnapshot }}{{ .ShortCommit }}
      {{- else }}{{ .Version }}
      {{- end }}
    {{- end -}}
    {{- with index .Env "DIRTY_SUFFIX" -}}
    {{ . }}
    {{- end -}}
    _checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
