version: 1

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm64
    main: ./cmd
    flags:
      - -v
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/primevprotocol/mev-commit/p2p.version={{.Version}}
      - -X github.com/primevprotocol/mev-commit/p2p.revision={{ .ShortCommit }}

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - image_templates:
    - ghcr.io/primevprotocol/mev-commit:v{{ .Major }}.{{ .Minor }}
    - ghcr.io/primevprotocol/mev-commit:latest
    dockerfile: Dockerfile.goreleaser
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
    - ghcr.io/primevprotocol/mev-commit:v{{ .Major }}.{{ .Minor }}
    - ghcr.io/primevprotocol/mev-commit:latest
    dockerfile: Dockerfile.goreleaser
    use: buildx
    goarch: arm64
    goarm: 7
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
