FROM alpine:latest

COPY mev-commit /usr/local/bin/mev-commit

EXPOSE 13522 13523 13524

LABEL org.opencontainers.image.source https://github.com/primev/mev-commit/tree/main/p2p

ENTRYPOINT ["mev-commit"]
