version: '3'

services:
  bootnode:
    build:
      context: ../
      dockerfile: ./p2p/integrationtest/Dockerfile
      args:
        node_type: bootnode
    restart: always
    volumes:
      - ./integrationtest/keys/bootnode:/key
    depends_on:
      - funder
    networks:
      primev_net:
        ipv4_address: 172.29.18.2
    ports:
      - "8080:13523"
    env_file:
      - integrationtest/.env
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]
    profiles:
      - e2etest
      - demo

  provider-1:
    build:
      context: ../
      dockerfile: ./p2p/integrationtest/Dockerfile
      args:
        node_type: provider
    restart: always
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/provider1:/key
    networks:
      - primev_net
    ports:
      - "8081:13523"
    env_file:
      - integrationtest/.env
    profiles:
      - minimal-setup
      - e2etest
      - demo
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  provider-emulator-1:
    build:
      context: ../
      dockerfile: ./p2p/integrationtest/provider/Dockerfile
    restart: always
    depends_on:
      - provider-1
    environment:
      - PROVIDER_IP=provider-1:13524
    networks:
      - primev_net
    ports:
      - "8082:8080"
    profiles:
      - minimal-setup
      - e2etest
      - demo
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  provider-2:
    build:
      context: ../
      dockerfile: ./p2p/integrationtest/Dockerfile
      args:
        node_type: provider
    restart: always
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/provider2:/key
    networks:
      - primev_net
    ports:
      - "8083:13523"
    env_file:
      - integrationtest/.env
    profiles:
      - e2etest
      - demo
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  provider-emulator-2:
    build:
      context: ../
      dockerfile: ./p2p/integrationtest/provider/Dockerfile
    restart: always
    depends_on:
      - provider-2
    environment:
      - PROVIDER_IP=provider-2:13524
    networks:
      - primev_net
    ports:
      - "8084:8080"
    profiles:
      - e2etest
      - demo
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  provider-3:
    build:
      context: ../
      dockerfile: ./p2p/integrationtest/Dockerfile
      args:
        node_type: provider
    restart: always
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/provider3:/key
    networks:
      - primev_net
    ports:
      - "8085:13523"
    env_file:
      - integrationtest/.env
    profiles:
      - e2etest
      - demo
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  provider-emulator-3:
    build:
      context: ../
      dockerfile: ./p2p/integrationtest/provider/Dockerfile
    restart: always
    depends_on:
      - provider-3
    environment:
      - PROVIDER_IP=provider-3:13524
    networks:
      - primev_net
    ports:
      - "8086:8080"
    profiles:
      - e2etest
      - demo
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]
  
  bidder-1:
    build:
      context: ../
      dockerfile: ./p2p/integrationtest/Dockerfile
      args:
        node_type: bidder
    restart: always
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/bidder1:/key
    networks:
      - primev_net
    ports:
      - "8087:13523"
    env_file:
      - integrationtest/.env
    profiles:
      - minimal-setup
      - e2etest
      - demo
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  bidder-emulator-1:
    build:
      context: ../
      dockerfile: ./p2p/integrationtest/real-bidder/Dockerfile
    restart: always
    depends_on:
      - bidder-1
    env_file:
      - integrationtest/.env
    environment:
      - BIDDER_IP=bidder-1:13524
    networks:
      - primev_net
    ports:
      - "8088:8080"
    profiles:
      - minimal-setup
      - e2etest
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  bidder-2:
    build:
      context: ../
      dockerfile: ./p2p/integrationtest/Dockerfile
      args:
        node_type: bidder
    restart: always
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/bidder2:/key
    networks:
      - primev_net
    ports:
      - "8089:13523"
    env_file:
      - integrationtest/.env
    profiles:
      - e2etest
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  bidder-emulator-2:
    build:
      context: ../
      dockerfile: ./p2p/integrationtest/real-bidder/Dockerfile
    restart: always
    depends_on:
      - bidder-2
    env_file:
      - integrationtest/.env
    environment:
      - BIDDER_IP=bidder-2:13524
    networks:
      - primev_net
    ports:
      - "8090:8080"
    profiles:
      - e2etest
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  bidder-3:
    build:
      context: ../
      dockerfile: ./p2p/integrationtest/Dockerfile
      args:
        node_type: bidder
    restart: always
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/bidder3:/key
    networks:
      - primev_net
    ports:
      - "8091:13523"
    env_file:
      - integrationtest/.env
    profiles:
      - e2etest
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  bidder-emulator-3:
    build:
      context: ../
      dockerfile: ./p2p/integrationtest/real-bidder/Dockerfile
    restart: always
    depends_on:
      - bidder-3
    env_file:
      - integrationtest/.env
    environment:
      - BIDDER_IP=bidder-3:13524
    networks:
      - primev_net
    ports:
      - "8092:8080"
    profiles:
      - e2etest
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  bidder-4:
    build:
      context: ../
      dockerfile: ./p2p/integrationtest/Dockerfile
      args:
        node_type: bidder
    restart: always
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/bidder4:/key
    networks:
      - primev_net
    ports:
      - "8093:13523"
    env_file:
      - integrationtest/.env
    profiles:
      - e2etest
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  bidder-emulator-4:
    build:
      context: ../
      dockerfile: ./p2p/integrationtest/real-bidder/Dockerfile
    restart: always
    depends_on:
      - bidder-4
    env_file:
      - integrationtest/.env
    environment:
      - BIDDER_IP=bidder-4:13524
    networks:
      - primev_net
    ports:
      - "8094:8080"
    profiles:
      - e2etest
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  bidder-5:
    build:
      context: ../
      dockerfile: ./p2p/integrationtest/Dockerfile
      args:
        node_type: bidder
    restart: always
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/bidder5:/key
    networks:
      - primev_net
    ports:
      - "8095:13523"
    env_file:
      - integrationtest/.env
    profiles:
      - e2etest
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  bidder-emulator-5:
    build:
      context: ../
      dockerfile: ./p2p/integrationtest/real-bidder/Dockerfile
    restart: always
    depends_on:
      - bidder-5
    env_file:
      - integrationtest/.env
    environment:
      - BIDDER_IP=bidder-5:13524
    networks:
      - primev_net
    ports:
      - "8096:8080"
    profiles:
      - e2etest
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  funder:
    build:
      context: ./integrationtest/foundry
    env_file:
      - integrationtest/.env
    networks:
      - primev_net
    profiles:
      - e2etest
      - demo

networks:
  primev_net:
    external: true