version: '3'

services:
  bootnode:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: bootnode
        service_name: bootnode
    restart: always
    volumes:
      - ./integrationtest/keys/bootnode:/key
    depends_on:
      - funder
    networks:
      primev_net:
        ipv4_address: 172.29.18.2
    ports:
      - "8080:13523"
    env_file:
      - integrationtest/.env
    profiles:
      - minimal-setup
      - integration-test
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  provider-1:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: provider
        service_name: provider1
    restart: always
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/provider1:/key
    networks:
      - primev_net
    ports:
      - "8081:13523"
    env_file:
      - integrationtest/.env
    profiles:
      - minimal-setup
      - integration-test
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  provider-emulator-1:
    build:
      context: .
      dockerfile: ./integrationtest/provider/Dockerfile
    restart: always
    depends_on:
      - provider-1
    environment:
      - PROVIDER_IP=provider-1:13524
    networks:
      - primev_net
    ports:
      - "8082:8080"
    profiles:
      - minimal-setup
      - integration-test
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  provider-2:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: provider
        service_name: provider2
    restart: always
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/provider2:/key
    networks:
      - primev_net
    ports:
      - "8083:13523"
    env_file:
      - integrationtest/.env
    profiles:
      - integration-test
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  provider-emulator-2:
    build:
      context: .
      dockerfile: ./integrationtest/provider/Dockerfile
    restart: always
    depends_on:
      - provider-2
    environment:
      - PROVIDER_IP=provider-2:13524
    networks:
      - primev_net
    ports:
      - "8084:8080"
    profiles:
      - integration-test
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  provider-3:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: provider
        service_name: provider3
    restart: always
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/provider3:/key
    networks:
      - primev_net
    ports:
      - "8085:13523"
    env_file:
      - integrationtest/.env
    profiles:
      - integration-test
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  provider-emulator-3:
    build:
      context: .
      dockerfile: ./integrationtest/provider/Dockerfile
    restart: always
    depends_on:
      - provider-3
    environment:
      - PROVIDER_IP=provider-3:13524
    networks:
      - primev_net
    ports:
      - "8086:8080"
    profiles:
      - integration-test
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  bidder-1:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: bidder
        service_name: bidder1
    restart: always
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/bidder1:/key
    networks:
      - primev_net
    ports:
      - "8087:13523"
    env_file:
      - integrationtest/.env
    profiles:
      - minimal-setup
      - integration-test
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  bidder-emulator-1:
    build:
      context: .
      dockerfile: integrationtest/bidder/Dockerfile
    restart: always
    depends_on:
      - bidder-1
    env_file:
      - integrationtest/.env
    environment:
      - BIDDER_IP=bidder-1:13524
    networks:
      - primev_net
    ports:
      - "8088:8080"
    profiles:
      - minimal-setup
      - integration-test
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  bidder-2:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: bidder
        service_name: bidder2
    restart: always
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/bidder2:/key
    networks:
      - primev_net
    ports:
      - "8089:13523"
    env_file:
      - integrationtest/.env
    profiles:
      - integration-test
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  bidder-emulator-2:
    build:
      context: .
      dockerfile: integrationtest/bidder/Dockerfile
    restart: always
    depends_on:
      - bidder-2
    env_file:
      - integrationtest/.env
    environment:
      - BIDDER_IP=bidder-2:13524
    networks:
      - primev_net
    ports:
      - "8090:8080"
    profiles:
      - integration-test
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  bidder-3:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: bidder
        service_name: bidder3
    restart: always
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/bidder3:/key
    networks:
      - primev_net
    ports:
      - "8091:13523"
    env_file:
      - integrationtest/.env
    profiles:
      - integration-test
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  bidder-emulator-3:
    build:
      context: .
      dockerfile: integrationtest/bidder/Dockerfile
    restart: always
    depends_on:
      - bidder-3
    env_file:
      - integrationtest/.env
    environment:
      - BIDDER_IP=bidder-3:13524
    networks:
      - primev_net
    ports:
      - "8092:8080"
    profiles:
      - integration-test
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  bidder-4:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: bidder
        service_name: bidder4
    restart: always
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/bidder4:/key
    networks:
      - primev_net
    ports:
      - "8093:13523"
    env_file:
      - integrationtest/.env
    profiles:
      - integration-test
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  bidder-emulator-4:
    build:
      context: .
      dockerfile: integrationtest/bidder/Dockerfile
    restart: always
    depends_on:
      - bidder-4
    env_file:
      - integrationtest/.env
    environment:
      - BIDDER_IP=bidder-4:13524
    networks:
      - primev_net
    ports:
      - "8094:8080"
    profiles:
      - integration-test
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  bidder-5:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: bidder
        service_name: bidder5
    restart: always
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/bidder5:/key
    networks:
      - primev_net
    ports:
      - "8095:13523"
    env_file:
      - integrationtest/.env
    profiles:
      - integration-test
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  bidder-emulator-5:
    build:
      context: .
      dockerfile: integrationtest/bidder/Dockerfile
    restart: always
    depends_on:
      - bidder-5
    env_file:
      - integrationtest/.env
    environment:
      - BIDDER_IP=bidder-5:13524
    networks:
      - primev_net
    ports:
      - "8096:8080"
    profiles:
      - integration-test
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  funder:
    build:
      context: ./integrationtest/foundry
    env_file:
      - integrationtest/.env
    networks:
      - primev_net
    profiles:
      - minimal-setup
      - integration-test

  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      - DD_API_KEY=${DD_KEY}
      - DD_TAGS=env:test
      - DD_SITE=datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE="name:datadog-agent"
    networks:
      primev_net:
        ipv4_address: 172.29.58.3
    profiles:
      - agent

networks:
  primev_net:
    external: true