FROM golang:1.21.4 AS builder

WORKDIR /app
COPY . .

RUN CGO_ENABLED=0 make user-cli

FROM alpine:latest

COPY --from=builder /app/bin/user_cli /usr/local/bin/user_cli

ENTRYPOINT ["user_cli", "bridge-to-settlement", "--amount", "2", "--dest-addr", "0xeE5d6F3eeF0ecB6EcbaCd51B7E3350B84882bc85", "--cancel-pending"]
