FROM golang:1.23.2 AS builder

WORKDIR /app
COPY ./bridge ./bridge
COPY ./contracts-abi ./contracts-abi
WORKDIR ./bridge/standard/bridge-v1
RUN CGO_ENABLED=0 make user-emulator

FROM alpine:latest

COPY --from=builder /app/bridge/standard/bridge-v1/bin/user_emulator /usr/local/bin/user_emulator

ENTRYPOINT ["user_emulator"]
