version: '3'
services:
  relayer:
    build:
      context: .
      dockerfile: Dockerfile.relayer
    networks:
      primev_net:
        ipv4_address: '172.29.0.117'
      geth-poa_l1_net:
        ipv4_address: '172.14.0.5'

  # Included as regression test for user cli entrypoint
  user_cli:
    build:
      context: .
      dockerfile: Dockerfile.user
    environment:
      PRIVATE_KEY: "0xe82a054e06f89598485134b4f2ce8a612ce7f7f7e14e650f9f20b30efddd0e57"
      LOG_LEVEL: "debug"
      L1_RPC_URL: "http://l1-bootnode:8545"
      SETTLEMENT_RPC_URL: "http://sl-bootnode:8545"
      L1_CHAIN_ID: "39999"
      SETTLEMENT_CHAIN_ID: "17864"
      L1_CONTRACT_ADDR: "0x1a18dfEc4f2B66207b1Ad30aB5c7A0d62Ef4A40b"
      SETTLEMENT_CONTRACT_ADDR: "0xc1f93bE11D7472c9B9a4d87B41dD0a491F1fbc75"
    networks:
      primev_net:
        ipv4_address: '172.29.0.103'
      geth-poa_l1_net:
        ipv4_address: '172.14.0.6'

  emulator_1:
    build:
      context: .
      dockerfile: Dockerfile.emulator
    environment:
      PRIVATE_KEY: "d821c54fd6dfd4c864202c125eaedb0a1fad7f40c81863fa3038338b475ff44a"
      ACCOUNT_ADDR: "0x0b1f1268f138aEEb12F54142B2359944904aaf6e"
      DD_API_KEY: ${DD_API_KEY}
      DD_APP_KEY: ${DD_APP_KEY}
    networks:
      primev_net:
        ipv4_address: '172.29.0.104'
      geth-poa_l1_net:
        ipv4_address: '172.14.0.7'

  emulator_2:
    build:
      context: .
      dockerfile: Dockerfile.emulator
    environment:
      PRIVATE_KEY: "6e7470ba919624df632ebe77cccda95f38e9376cf2e7e3cb42726cb23457abae"
      ACCOUNT_ADDR: "0x9D58dB6c050E0E708b06c8e40aE803b5c0a793B0"
      DD_API_KEY: ${DD_API_KEY}
      DD_APP_KEY: ${DD_APP_KEY}
    networks:
      primev_net:
        ipv4_address: '172.29.0.105'
      geth-poa_l1_net:
        ipv4_address: '172.14.0.8'

  emulator_3:
    build:
      context: .
      dockerfile: Dockerfile.emulator
    environment:
      PRIVATE_KEY: "25710d3869ef44b2f026615c0734ff3f44c17d319f7fc6db318f0cacece3d575"
      ACCOUNT_ADDR: "0x911FA3b5D45c1A5E6316830dd5B3fCcce1b421FF"
      DD_API_KEY: ${DD_API_KEY}
      DD_APP_KEY: ${DD_APP_KEY}
    networks:
      primev_net:
        ipv4_address: '172.29.0.106'
      geth-poa_l1_net:
        ipv4_address: '172.14.0.9'

  emulator_4:
    build:
      context: .
      dockerfile: Dockerfile.emulator
    environment:
      PRIVATE_KEY: "a5743a07de65be93c11e1814bfcf4b00d3e49d0e84cd488e6cb98ba4410d585f"
      ACCOUNT_ADDR: "0xAA7E52aF3c86Aa8b617670347024e86C3b26bcd8"
      DD_API_KEY: ${DD_API_KEY}
      DD_APP_KEY: ${DD_APP_KEY}
    networks:
      primev_net:
        ipv4_address: '172.29.0.107'
      geth-poa_l1_net:
        ipv4_address: '172.14.0.10'

  emulator_5:
    build:
      context: .
      dockerfile: Dockerfile.emulator
    environment:
      PRIVATE_KEY: "865a133ee5b85c4f4970be2f6ac590a7c4be51b936df48028f0285bed12f1f10"
      ACCOUNT_ADDR: "0x72F17F6a137645B774c3a115530410732019fE84"
      DD_API_KEY: ${DD_API_KEY}
      DD_APP_KEY: ${DD_APP_KEY}
    networks:
      primev_net:
        ipv4_address: '172.29.0.108'
      geth-poa_l1_net:
        ipv4_address: '172.14.0.11'

  datadog-agent:
    image: datadog/agent:latest
    container_name: datadog-agent
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_TAGS=env:relayer-test
      - DD_SITE=datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE=image:datadog/agent:*
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    depends_on:
      - relayer
    networks:
      primev_net:
        ipv4_address: '172.29.4.118' 
    profiles:
      - dd_agent

networks:
  primev_net:
    external: true
  geth-poa_l1_net:
    external: true
