# Default values for mev-commit-p2p.

nameOverride: ""
fullnameOverride: ""

global:
  # Docker image configuration
  image:
    repository: harshsingh07/flood
    tag: mev-commit-p2p-1.1.1
    pullPolicy: IfNotPresent

  # TLS certificate configuration
  tls:
    selfSigned: true
    existingSecret: ""
    forceRegenerate: false
    validityDays: 365

  # External Secret Operator configuration
  externalSecrets:
    enabled: false
    secretStore: "aws-secretsmanager"
    secretStoreKind: "ClusterSecretStore"
    nodeSecretKey: "mev-commit-node-secrets"
    tlsSecretKey: "mev-commit-tls"

  # Persistence configuration
  persistence:
    enabled: true
    storageClass: "premium-rwo"
    dataSize: "10Gi"
    keystoreSize: "2Mi"

  # Logging configuration
  logging:
    format: "json"
    level: "info"
    additionalTags: ""

  # Contract addresses
  contracts:
    bidderRegistry: "0x434d37D48A5eF225E8B103fA5Fb6A5a8ac32d7FF"
    providerRegistry: "0x50BaB3F4420Eb2533d326D15838110FDfd944c97"
    preconfStore: "0x3065fD5e5e04582aDAA5C0Ae63F0eD12cca85007"
    blockTracker: "0x2aE6b4339768A13dc8D607792120Ad7b26DD8232"
    validatorRouter: "0xb38cd2caa7F5D11f597A56430D138Ab580615d8D"

  # Gas settings for transactions
  gas:
    limit: "2000000"
    tipCap: "50000000"
    feeCap: "60000000"

  # RPC endpoints
  rpc:
    settlementEndpoint: "http://snode-geth-archive-leader.default.svc.cluster.local:8545"
    settlementWsEndpoint: "ws://snode-geth-archive-leader.default.svc.cluster.local:8546"
    l1Endpoint: "http://mev-commit-mock-l1.default.svc.cluster.local:8545"

  # Notifications
  notifications:
    bufferCapacity: "100"

  # Ethereum chain configuration
  laggardMode: "10"

# Node configuration template (bootnode, provider, or bidder)
node:
  type: "bootnode"
  replicas: 1

  service:
    type: ClusterIP
    annotations: {}
    nodePorts:
      http: null
      p2p: null
      rpc: null

  ports:
    http: 13523
    p2p: 13522
    rpc: 13524

  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0

  podSecurityContext:
    fsGroup: 0

  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi

  bootnodeConnectionString: ""

  defaultKeystorePassword: "changeme"
  defaultP2PSecret: ""
  existingSecret: ""

  nodeSelector: {}
  tolerations: []
  affinity: {}

  podAnnotations: {}
  imagePullSecrets: []

# Explicit config for use in ConfigMap
keystore:
  path: "/p2p-keystore"
