nameOverride: ""
fullnameOverride: ""

global:
  image:
    repository: harshsingh07/flood
    tag: mev-commit-p2p-1.1.1
    pullPolicy: IfNotPresent

  tls:
    selfSigned: true
    existingSecret: ""

  externalSecrets:
    enabled: false
    secretStore: "aws-cluster-secret-store"
    secretStoreKind: "ClusterSecretStore"
    nodeSecretKey: "mev-commit-node-secrets"

  persistence:
    enabled: true
    storageClass: "premium-rwo"
    dataSize: "10Gi"
    keystoreSize: "5Mi"

  logging:
    format: "json"
    level: "info"
    additionalTags: ""

  gas:
    limit: "2000000"
    tipCap: "50000000"
    feeCap: "60000000"

  rpc:
    settlementEndpoint: "http://snode-geth-archive-leader.default.svc.cluster.local:8545"
    settlementWsEndpoint: "ws://snode-geth-archive-leader.default.svc.cluster.local:8546"
    l1Endpoint: "http://mev-commit-mock-l1.default.svc.cluster.local:8545"

  notifications:
    bufferCapacity: "100"

  laggardMode: "10"

# Node-specific config
node:
  type: "bootnode"
  replicas: 1
    # Run as root user
  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0

  podSecurityContext:
    fsGroup: 0

  service:
    type: ClusterIP
    annotations: {}
    nodePorts:
      http: null
      p2p: null
      rpc: null

  ports:
    http: 13523
    p2p: 13522
    rpc: 13524

  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0

  podSecurityContext:
    fsGroup: 0

  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi

  bootnodeConnectionString: ""

  defaultKeystorePassword: "harsh"
  defaultP2PSecret: ""
  existingSecret: ""

  nodeSelector: {}
  tolerations: []
  affinity: {}

  podAnnotations: {}
  imagePullSecrets: []

# Used in configMap to override MEV_COMMIT_KEYSTORE_PATH
keystore:
  path: "/keystore"
  downloadUrl: "https://raw.githubusercontent.com/harshsingh1002/eth-poa-test/refs/heads/main/keystores/keystore14/UTC--2025-06-11T17-06-14.424583000Z--58d029280170d3cd915525e95ec287b7a7fb575b"
  retries: 3

