FROM golang:1.23.0-alpine AS builder

WORKDIR /app

COPY p2p/go.mod p2p/go.sum /app/p2p/
COPY x/go.mod x/go.sum /app/x/
COPY contracts-abi/go.mod contracts-abi/go.sum /app/contracts-abi/

RUN cd /app/p2p && go mod download
RUN cd /app/x && go mod download
RUN cd /app/contracts-abi && go mod download

COPY . .

RUN go build -o /app/mev-commit ./p2p/cmd

FROM alpine:3.10

COPY --from=builder /app/mev-commit /usr/local/bin/mev-commit

ENTRYPOINT ["mev-commit"]
