ARG MEV_COMMIT_BUILDER_VERSION=latest
FROM mev-commit-builder:{$MEV_COMMIT_BUILDER_VERSION} AS builder
FROM alpine:3.10

COPY --from=builder /go/bin/provider /usr/local/bin/provider-emulator
COPY --from=builder /scripts/provider-emulator-entrypoint.sh entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
