ARG MEV_COMMIT_BUILDER_VERSION=latest
FROM mev-commit-builder:{$MEV_COMMIT_BUILDER_VERSION} AS builder
FROM alpine:3.10

COPY --from=builder /go/bin/l1-transaction-emulator /usr/local/bin/l1-transactor

ENTRYPOINT ["l1-transactor"]
