ARG MEV_COMMIT_BUILDER_VERSION=latest
FROM mev-commit-builder:{$MEV_COMMIT_BUILDER_VERSION} AS builder
FROM alpine:3.10

COPY --from=builder /go/bin/relay-emulator /usr/local/bin/relay-emulator

ENTRYPOINT ["relay-emulator"]
