version: '3'
services:
  hyperlane-deployer:
    build:
      context: ./hyperlane-deployer
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "test -f /hyperlane-monorepo/artifacts/done-warp-route || exit 1"]
      interval: 5s
      retries: 100
    environment:
      - HYPERLANE_DEPLOYER_PRIVATE_KEY=${HYPERLANE_DEPLOYER_PRIVATE_KEY}
      - SEPOLIA_RPC_URL=${SEPOLIA_RPC_URL}
    networks:
      primev_net:
        ipv4_address: '172.29.0.50'
    volumes:
      - hyperlane-deploy-artifacts:/hyperlane-monorepo/artifacts
    profiles:
      - bridge
  
  hyperlane-validator1:
    build:
      context: ./hyperlane-validator
      dockerfile: Dockerfile
      args:
        # Image can be built for arm64 with https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/main/rust/build.sh
        - AGENT_BASE_IMAGE=${AGENT_BASE_IMAGE}
        - SETTLEMENT_RPC_URL=${SETTLEMENT_RPC_URL}
    # Reuse geth private key for validator
    command: ./validator --validator.key ${NODE1_PRIVATE_KEY} --chains.mevcommitsettlement.signer.key ${NODE1_PRIVATE_KEY} --checkpointSyncer.path /val1-sigs
    # TODO: evaluate why container needs to run as root
    user: "0:0"
    depends_on:
      hyperlane-deployer:
        condition: service_healthy
    networks:
      primev_net:
        ipv4_address: '172.29.0.75'
    volumes:
      - hyperlane-deploy-artifacts:/deploy-artifacts
      - hyperlane-validator1-sigs:/val1-sigs
      - hyperlane-validator1-db:/val-db
    profiles:
      - bridge
  
  hyperlane-validator2:
    build:
      context: ./hyperlane-validator
      dockerfile: Dockerfile
      args:
        - AGENT_BASE_IMAGE=${AGENT_BASE_IMAGE}
        - SETTLEMENT_RPC_URL=${SETTLEMENT_RPC_URL}
    # Reuse geth private key for validator
    command: ./validator --validator.key ${NODE2_PRIVATE_KEY} --chains.mevcommitsettlement.signer.key ${NODE2_PRIVATE_KEY} --checkpointSyncer.path /val2-sigs
    # TODO: evaluate why container needs to run as root
    user: "0:0"
    depends_on:
      hyperlane-deployer:
        condition: service_healthy
    networks:
      primev_net:
        ipv4_address: '172.29.0.76'
    volumes:
      - hyperlane-deploy-artifacts:/deploy-artifacts
      - hyperlane-validator2-sigs:/val2-sigs
      - hyperlane-validator2-db:/val-db
    profiles:
      - bridge
  
  hyperlane-relayer:
    build:
      context: ./hyperlane-relayer
      dockerfile: Dockerfile
      args:
        - AGENT_BASE_IMAGE=${AGENT_BASE_IMAGE}
    user: "0:0"
    depends_on:
      hyperlane-deployer:
        condition: service_healthy
    environment:
      - RELAYER_PRIVATE_KEY=${RELAYER_PRIVATE_KEY}
      - SETTLEMENT_RPC_URL=${SETTLEMENT_RPC_URL}
      - SEPOLIA_RPC_URL=${SEPOLIA_RPC_URL}
    networks:
      primev_net:
        ipv4_address: '172.29.0.77'
    volumes:
      - hyperlane-deploy-artifacts:/deploy-artifacts
      - hyperlane-validator1-sigs:/val1-sigs
      - hyperlane-validator2-sigs:/val2-sigs
      - hyperlane-relayer-db:/relayer-db
    profiles:
      - bridge
  
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #     args:
  #       - NEXT_PUBLIC_WALLET_CONNECT_ID=${NEXT_PUBLIC_WALLET_CONNECT_ID}
  #   depends_on:
  #     hyperlane-deployer:
  #       condition: service_healthy
  #   environment:
  #     - NEXT_PUBLIC_WALLET_CONNECT_ID=${NEXT_PUBLIC_WALLET_CONNECT_ID}
  #     - SETTLEMENT_RPC_URL=${SETTLEMENT_RPC_URL}
  #     - PUBLIC_SETTLEMENT_RPC_URL=${PUBLIC_SETTLEMENT_RPC_URL}
  #   networks:
  #     primev_net:
  #       ipv4_address: '172.29.0.90'
  #   ports:
  #     - 80:3000
  #   volumes:
  #     - hyperlane-deploy-artifacts:/deploy-artifacts
  #   profiles:
  #     - bridge
  
  emulator1:
    build:
      context: ../
      dockerfile: hyperlane/user-emulator/Dockerfile
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_APP_KEY=${DD_APP_KEY}
      - SETTLEMENT_RPC_URL=${SETTLEMENT_RPC_URL}
      - SEPOLIA_RPC_URL=${SEPOLIA_RPC_URL}
      - EMULATOR_PRIVATE_KEY=${EMULATOR1_PRIVATE_KEY}
      - EMULATOR_ADDRESS=0x04F713A0b687c84D4F66aCd1423712Af6F852B78
    volumes:
      - hyperlane-deploy-artifacts:/deploy-artifacts
    networks:
      primev_net:
        ipv4_address: '172.29.0.171'
    profiles:
      - 1-emulators
      - 2-emulators
      - 3-emulators
      - 4-emulators
      - 5-emulators
    
  emulator2:
    build:
      context: ../
      dockerfile: hyperlane/user-emulator/Dockerfile
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_APP_KEY=${DD_APP_KEY}
      - SETTLEMENT_RPC_URL=${SETTLEMENT_RPC_URL}
      - SEPOLIA_RPC_URL=${SEPOLIA_RPC_URL}
      - EMULATOR_PRIVATE_KEY=${EMULATOR2_PRIVATE_KEY}
      - EMULATOR_ADDRESS=0x4E2D04c65C399Eb27B3E3ADA06110BCd47b5a506
    volumes:
      - hyperlane-deploy-artifacts:/deploy-artifacts
    networks:
      primev_net:
        ipv4_address: '172.29.0.172'
    profiles:
      - 2-emulators
      - 3-emulators
      - 4-emulators
      - 5-emulators

  emulator3:
    build:
      context: ../
      dockerfile: hyperlane/user-emulator/Dockerfile
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_APP_KEY=${DD_APP_KEY}
      - SETTLEMENT_RPC_URL=${SETTLEMENT_RPC_URL}
      - SEPOLIA_RPC_URL=${SEPOLIA_RPC_URL}
      - EMULATOR_PRIVATE_KEY=${EMULATOR3_PRIVATE_KEY}
      - EMULATOR_ADDRESS=0x7AEe7AD6b2EAd96532D84D20358Db0e697f060Cd
    volumes:
      - hyperlane-deploy-artifacts:/deploy-artifacts
    networks:
      primev_net:
        ipv4_address: '172.29.0.173'
    profiles:
      - 3-emulators
      - 4-emulators
      - 5-emulators
  
  emulator4:
    build:
      context: ../
      dockerfile: hyperlane/user-emulator/Dockerfile
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_APP_KEY=${DD_APP_KEY}
      - SETTLEMENT_RPC_URL=${SETTLEMENT_RPC_URL}
      - SEPOLIA_RPC_URL=${SEPOLIA_RPC_URL}
      - EMULATOR_PRIVATE_KEY=${EMULATOR4_PRIVATE_KEY}
      - EMULATOR_ADDRESS=0x765235CDda5FC6a620Fea2208A333a97CEDA2E1d
    volumes:
      - hyperlane-deploy-artifacts:/deploy-artifacts
    networks:
      primev_net:
        ipv4_address: '172.29.0.174'
    profiles:
      - 4-emulators
      - 5-emulators
  
  emulator5:
    build:
      context: ../
      dockerfile: hyperlane/user-emulator/Dockerfile
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_APP_KEY=${DD_APP_KEY}
      - SETTLEMENT_RPC_URL=${SETTLEMENT_RPC_URL}
      - SEPOLIA_RPC_URL=${SEPOLIA_RPC_URL}
      - EMULATOR_PRIVATE_KEY=${EMULATOR5_PRIVATE_KEY}
      - EMULATOR_ADDRESS=0x163c7bD4C3B815B06503D8E8B5906519C319EA6f
    volumes:
      - hyperlane-deploy-artifacts:/deploy-artifacts
    networks:
      primev_net:
        ipv4_address: '172.29.0.175'
    profiles:
      - 5-emulators
  
  datadog-agent:
    image: datadog/agent:latest
    container_name: datadog-agent
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_TAGS=env:relayer-test
      - DD_SITE=datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE=image:datadog/agent:*
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    depends_on:
      - hyperlane-relayer
    networks:
      primev_net:
        ipv4_address: '172.29.4.118' 
    profiles:
      - dd_agent

networks:
  primev_net:
    external: true

volumes:
  hyperlane-deploy-artifacts:
  hyperlane-validator1-sigs:
  hyperlane-validator2-sigs:
  hyperlane-validator1-db:
  hyperlane-validator2-db:
  hyperlane-relayer-db:
