apiVersion: v1
kind: Service
metadata:
  name: {{ include "snode-geth.fullname" . }}
  labels:
    {{- include "snode-geth.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      name: {{ .name }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "snode-geth.serviceSelector" . | nindent 4 }}
