name: Smart Contracts Actions

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check:
    name: Foundry Checks and Reports
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run tests
        run: forge test -vvv --via-ir

      - name: Run snapshot
        run: forge snapshot --via-ir

      - name: Run coverage
        run: forge coverage --ir-minimum

  build:
    name: Hardhat Checks and Scripts
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      # Install Hardhat globally
      - run: npm install -g hardhat

      # Install project dependencies
      - run: npm install

      # Build the project, if applicable
      - run: npm run build --if-present
