apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mev-commit-p2p.fullname" . }}-{{ .Values.node.type }}
  labels:
    app.kubernetes.io/name: {{ include "mev-commit-p2p.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Values.node.type }}
    {{- include "mev-commit-p2p.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mev-commit-p2p.fullname" . }}-{{ .Values.node.type }}
  replicas: {{ .Values.node.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mev-commit-p2p.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: {{ .Values.node.type }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mev-commit-p2p.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: {{ .Values.node.type }}
    spec:
      securityContext:
        {{- toYaml .Values.node.podSecurityContext | nindent 8 }}

      initContainers:
        - name: keystore-init
          image: "alpine/curl:8.5.0"
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "/scripts/keystore-init.sh"]
          env:
            - name: KEYSTORE_PATH
              value: "{{ .Values.keystore.path }}"
            - name: KEYSTORE_DOWNLOAD_URL
              value: "{{ .Values.keystore.downloadUrl }}"
            - name: KEYSTORE_RETRIES
              value: "{{ .Values.keystore.retries | default "3" }}"
          volumeMounts:
            - name: keystore
              mountPath: /keystore
            - name: init-scripts
              mountPath: /scripts
              readOnly: true
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
                - DAC_OVERRIDE

      containers:
        - name: {{ .Values.node.type }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command: ["mev-commit"]
          ports:
            - name: http
              containerPort: {{ .Values.node.ports.http }}
              protocol: TCP
            - name: p2p
              containerPort: {{ .Values.node.ports.p2p }}
              protocol: TCP
            - name: rpc
              containerPort: {{ .Values.node.ports.rpc }}
              protocol: TCP
          env:
            - name: MEV_COMMIT_NAT_ADDR
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: {{ include "mev-commit-p2p.fullname" . }}-{{ .Values.node.type }}-config
            - secretRef:
                name: {{ include "mev-commit-p2p.fullname" . }}-{{ .Values.node.type }}-secrets
          securityContext:
            {{- toYaml .Values.node.securityContext | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: keystore
              mountPath: /keystore
            - name: tls-certs
              mountPath: /certs

      volumes:
        - name: tls-certs
          secret:
            secretName: {{ include "mev-commit-p2p.fullname" . }}-tls
        - name: init-scripts
          configMap:
            name: {{ include "mev-commit-p2p.fullname" . }}-{{ .Values.node.type }}-init
            defaultMode: 0755

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.global.persistence.storageClass | default "premium-rwo" }}
        resources:
          requests:
            storage: {{ .Values.global.persistence.dataSize | default "10Gi" }}
    - metadata:
        name: keystore
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.global.persistence.storageClass | default "premium-rwo" }}
        resources:
          requests:
            storage: {{ .Values.global.persistence.keystoreSize | default "5Mi" }}
