chainId: 
genesisUrl: "https://raw.githubusercontent.com/harshsingh1002/eth-poa-test/refs/heads/main/devnet4/genesis/genesis.json"

replicas: 1

signer:
  passwordExternalSecret:
    enabled: false

  privateKeyExternalSecret:
    enabled: false

image:
  repository: harshsingh07/mev-commit-poa-geth
  tag: arm64-latest

resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "2000m"
    memory: "8Gi"

persistence:
  enabled: true
  size: 25Gi
  storageClassName: standard

ports:
  p2p: 30303
  http: 8545
  ws: 8546

init:
  image:
    repository:  ethereum/client-go
    tag: alltools-v1.14.13

probes:
  enabled: false
  headlagProbeThreshold: 3600
  readiness:
    checks:
      - syncProbe.sh
    initialDelay: 30
    periodSeconds: 120
    successThreshold: 3
    failureThreshold: 5

nodeConfig:
  httpApi: "eth,net,web3,clique"
  wsApi: "eth,net,web3,clique"
