priv-key-file: /key
peer-type: provider
p2p-port: 13522
http-port: 13523
rpc-port: 13524
secret: hello
log-fmt: json
log-level: debug
server-tls-certificate: /server-cert.pem
server-tls-private-key: /server-key.pem
preconf-contract: <PRECONF_CONTRACT>
bidder-registry-contract: <BIDDER_REGISTRY>
provider-registry-contract: <PROVIDER_REGISTRY>
settlement-rpc-endpoint: <RPC_URL>
bootnodes:
  - /ip4/172.29.18.2/tcp/13522/p2p/16Uiu2HAmLYUvthfDCewNMdfPhrVefBbsfaPL22fWWfC2zuoh5SpV
