name: mev-commit-oracle-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go 1.21.1
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.1
      id: go

    - name: Lint with golangci-lint v1.54.2
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.54.2

    - name: Vet
      run: go vet ./...

    - name: Build
      run: go build ./...

    - name: Test
      run: go test -short ./...

