{{- if .Values.global.externalSecrets.enabled }}
---
{{- if not .Values.global.tls.selfSigned }}
# External Secret for TLS certificates (only if not using self-signed certs)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "mev-commit-p2p.fullname" . }}-tls-secret
  labels:
    {{- include "mev-commit-p2p.labels" . | nindent 4 }}
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: {{ .Values.global.externalSecrets.secretStore }}
    kind: {{ .Values.global.externalSecrets.secretStoreKind | default "ClusterSecretStore" }}
  target:
    name: {{ include "mev-commit-p2p.fullname" . }}-tls
    creationPolicy: Owner
  data:
    - secretKey: tls.crt
      remoteRef:
        key: {{ .Values.global.externalSecrets.tlsSecretKey | default (printf "%s-tls" (include "mev-commit-p2p.fullname" .)) }}
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: {{ .Values.global.externalSecrets.tlsSecretKey | default (printf "%s-tls" (include "mev-commit-p2p.fullname" .)) }}
        property: tls.key
{{- end }}

---
# External Secret for node secrets - only the sensitive ones you specified
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "mev-commit-p2p.fullname" . }}-node-secrets
  labels:
    {{- include "mev-commit-p2p.labels" . | nindent 4 }}
spec:
  refreshInterval: "12h"
  secretStoreRef:
    name: {{ .Values.global.externalSecrets.secretStore }}
    kind: {{ .Values.global.externalSecrets.secretStoreKind | default "ClusterSecretStore" }}
  target:
    name: {{ include "mev-commit-p2p.fullname" . }}-node-secrets
    creationPolicy: Owner
  data:
    # The only two sensitive environment variables per your list
    - secretKey: MEV_COMMIT_KEYSTORE_PASSWORD
      remoteRef:
        key: {{ .Values.global.externalSecrets.nodeSecretKey | default (printf "%s-node-secrets" (include "mev-commit-p2p.fullname" .)) }}
        property: keystore-password
    - secretKey: MEV_COMMIT_SECRET
      remoteRef:
        key: {{ .Values.global.externalSecrets.nodeSecretKey | default (printf "%s-node-secrets" (include "mev-commit-p2p.fullname" .)) }}
        property: p2p-secret
{{- end }}
