apiVersion: v1
kind: Secret
metadata:
  name: {{ include "preconf-rpc.fullname" . }}-blocknative-api-key
  labels:
    {{- include "preconf-rpc.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.blocknative.apiKey | b64enc | quote }}
