#!/usr/bin/env bash

BACKEND_IP_ADDRESS=$1
FRONTEND_IP_ADDRESS=$2

if [ -z "${BACKEND_IP_ADDRESS}" || -z "${FRONTEND_IP_ADDRESS}" ]; then
    echo "Usage: $0 <BACKEND_IP_ADDRESS> <FRONTEND_IP_ADDRESS>"
    exit 1
fi

BLOCKSCOUT_ALL_IN_ONE_DIR="./docker-compose"
BLOCKSCOUT_ALL_IN_ONE_URL="https://mev-commit.s3.us-west-2.amazonaws.com/blockscout-docker-compose.tar.gz"

wget -qO- ${BLOCKSCOUT_ALL_IN_ONE_URL} | tar -xvzf -

cat <<EOH > "${BLOCKSCOUT_ALL_IN_ONE_DIR}/.backend.env"
BLOCK_TRANSFORMER=clique
ETHEREUM_JSONRPC_VARIANT=geth
ETHEREUM_JSONRPC_HTTP_URL=http://${BACKEND_IP_ADDRESS}:8555/
ETHEREUM_JSONRPC_TRACE_URL=http://${BACKEND_IP_ADDRESS}:8555/
ETHEREUM_JSONRPC_WS_URL=ws://${BACKEND_IP_ADDRESS}:8556/
CHAIN_ID=17864
EOH

cat <<EOH > "${BLOCKSCOUT_ALL_IN_ONE_DIR}/.frontend.env"
NEXT_PUBLIC_API_HOST=${FRONTEND_IP_ADDRESS}
NEXT_PUBLIC_STATS_API_HOST=http://${FRONTEND_IP_ADDRESS}:8080
NEXT_PUBLIC_VISUALIZE_API_HOST=http://${FRONTEND_IP_ADDRESS}:8081
NEXT_PUBLIC_APP_HOST=${FRONTEND_IP_ADDRESS}
NEXT_PUBLIC_NETWORK_NAME=primev-testnet
EOH

cp docker-compose.yml "${BLOCKSCOUT_ALL_IN_ONE_DIR}/"
docker compose -f "${BLOCKSCOUT_ALL_IN_ONE_DIR}/docker-compose.yml" up -d
