name: releaser

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    strategy:
      matrix:
        module: [ bridge/standard/bridge-v1, external/geth, oracle, p2p ]

    steps:
      - if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: echo "FLAGS=--snapshot" >> ${GITHUB_ENV}

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.work.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          check-latest: true
          cache-dependency-path: go.work.sum

# TODO(mrekucci): Re-enable when the repo is finalized.
#      - name: GHCR Docker Login
#        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
#      - name: Setup Docker Buildx
#        uses: docker/setup-buildx-action@v3

      - name: Release
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --config=./${{ matrix.module }}/.goreleaser.yml --clean ${{ env.FLAGS }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

